# version: '3'
services:
  mongodb:
    image: "mongo"
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
      # - home/htmlgenerator/db-backup:/data/db
    networks:
      - html-generator-network

  backend:
    build: ./backend
    container_name: nodejs-api
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - html-generator-network

  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - "3800:3800"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - html-generator-network

networks:
  html-generator-network:
    driver: bridge

volumes:
  data:
  logs: